spring:
  security:
    user:
      name: leticia
      password: minhaSenhaSegura123
  datasource:
    url: jdbc:postgresql://localhost:5432/FoodOrderingSystem
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword
  logging:
    level:
      org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

server:
  port: 8080
